name: neekesh
favicon: null
layout_spectrum: 0.97615
typography_spectrum: 0.88085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5897fe'
    - '#9bcdff'
    - '#71604f'
    - '#f1f8fe'
    - '#092940'
  brandStrength: 0.6499042031355202
  lightness: 0.7714751840103418
  saturation: 0.7669545817188919
  rhythmicContrast: 0.36607854324392974
purpose: []
