name: neekesh
favicon: null
layout_spectrum: 0.77297
typography_spectrum: 0.88085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5897fe'
    - '#9bcdff'
    - '#71604f'
    - '#f1f8fe'
    - '#092940'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
