name: 'Neekesh V. Dharia, MD PhD'
favicon: null
layout_spectrum: 0.51502
typography_spectrum: 0.88085
title: 'Neekesh V. Dharia, MD PhD'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe0e5'
    - '#282828'
    - '#ababab'
    - '#575757'
    - '#828282'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
